sudo: required
language: python
python:
- '3.6'
services:
- docker
- memcached
env:
  global:
  - RELEASE_NAME="course-roster"
  - DJANGO_APP="course_roster"
  - COMMIT_HASH="$(git rev-parse --short=7 HEAD)"
  - IMAGE_TAG="${RELEASE_NAME}:${COMMIT_HASH}"
  - DEPLOY_SCRIPT=https://raw.githubusercontent.com/uw-it-aca/gcp-app-deploy/master/travis-ci/deploy.sh
  - GCP_JSON_KEY=gcp.json
  - secure: ZNiqZIVmgLToN4SqUKxIIOrPfMgwczr0xpoS9hk6Xx9wnTLcTwAg/Z8Fg6xYo9Ue8qGTTPLuwK6kB63q2pqN3PcVg6v4H6LR7546zPHeEVBSIOojif0gytlmoLEy5I+WZZ4Soa8nNvBiF/5yBXUV2YNV/jeN4QK8Q4x/yQwjLguAn4Z6fBPEURXYWrZdvv0+nLb3Hj5Ju8f5jFkVpZG0vQhbYyh6RMLXKFCOfeTTN86EdGUW6bMKEf1lXrCACvyrfTP2kZSu5x1Lpl2gLjJtDaqPOOL8DOPLfsGi8AFn+Hr/V5uwiuxc9OJYWTcta48Xe0uaVFTo1jub6z2LGAYEaHqi7PiLneyWqSWRIsoklYTdtEA+vyqz/z0g34ZYJrQCceacNKAd1kc/OZ+TKoanvN8ow4dAW3kEwAyodnMHggffB5IjPOppv0dJkYcLGCy1T02WTXC61J/gk+K6We8Yk/F2epXT1e6kulkku95ju3QUv12V821QV3grkQCs0gLCm1nH5PZdefwmUb3NpqZgtgV8+cxM9iZknIZ0uznyaiwJ58h01KuhHQcBnHSpQwoRwwjC1reb714sCZ5/q1QN2ri6/MVMlo9xmDGCBn6jFaJZK95nw83vAcrgRETSx0+N0waZ8yrOSgaseGk33njIijKkPmtI3w9tL/8P2m4N2PU=
install:
- docker build --target app-container -t "$IMAGE_TAG" .
- docker build -t app-test-container .
before_script:
- pip install coverage
- pip install coveralls
script:
- docker run -u root -it -v /tmp:/coverage -e DJANGO_APP="$DJANGO_APP" -e "ENV=localdev"
  -e "AUTH=BLTI_DEV" app-test-container bash -c ". ./travis-ci/test.sh"
after_success:
- cp /tmp/.coverage.* .
- coverage combine
- coveralls
- openssl aes-256-cbc -K $encrypted_0e718fcdeb51_key -iv $encrypted_0e718fcdeb51_iv
  -in gcp.json.enc -out gcp.json -d
deploy:
- provider: script
  skip_cleanup: true
  script: curl -Ls "$DEPLOY_SCRIPT" | bash
  on:
    all_branches: true
    condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH =~ ^(master|develop)$
